apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spp-event-bot-data
  namespace: matrix
  labels:
    app.kubernetes.io/name: spp-event-bot
    app.kubernetes.io/component: bot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
