apiVersion: v1
kind: Service
metadata:
  name: matrix-site
  namespace: matrix
  labels:
    app.kubernetes.io/name: matrix-site
spec:
  selector:
    app.kubernetes.io/name: matrix-site
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
