apiVersion: v1
kind: Secret
metadata:
  name: mautrix-discord-db-credentials
  namespace: matrix
type: kubernetes.io/basic-auth
stringData:
  # Used by CNPG to bootstrap the PostgreSQL database
  # Generate with: openssl rand -hex 32
  username: mautrix_discord
  password: "CHANGE_ME"
