apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mautrix-discord-data
  namespace: matrix
  labels:
    app.kubernetes.io/name: mautrix-discord
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
