apiVersion: v1
kind: Service
metadata:
  name: mautrix-discord
  namespace: matrix
  labels:
    app.kubernetes.io/name: mautrix-discord
spec:
  selector:
    app.kubernetes.io/name: mautrix-discord
  ports:
    - name: appservice
      port: 29334
      targetPort: 29334
      protocol: TCP
  type: ClusterIP
